<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>WpfHelper</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <Platforms>x64;x86</Platforms>
    <RootNamespace>WpfHelper</RootNamespace>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Import Project="Props\OutputLibs.props" />

  <ItemGroup>
    <ProjectReference Include="..\Cli.Net8\Wrapper.Net80.vcxproj" />
  </ItemGroup>

  <Import Project="$(MSBuildThisFileDirectory)Targets.props" />

  <ItemGroup>
    <Compile Include="AssemblyInfo.cs" />
  </ItemGroup>

</Project>
