<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup>
    <BswmThisDir>$(MSBuildThisFileDirectory)</BswmThisDir>
  </PropertyGroup>

  <Import Project="$(BswmThisDir)WpfHelper\WpfHelper.props" />
  <Import Project="$(BswmThisDir)Editor/MatrixEditor/Targets.props" />

  <ItemGroup>
    <Compile Include="$(BswmThisDir)Models\DocumentSummary.cs" />
    <Compile Include="$(BswmThisDir)Models\MatrixInfo.cs" />
    <Compile Include="$(BswmThisDir)Models\RankingModel.cs" />
    <Compile Include="$(BswmThisDir)Models\ScoreDocument.cs" />
    <Compile Include="$(BswmThisDir)Models\VictoryLine.cs" />

    <Compile Include="$(BswmThisDir)Services\AbstractWindowService.cs" />
    <Compile Include="$(BswmThisDir)Services\DialogSettings.cs" />
    <Compile Include="$(BswmThisDir)Services\IWindowService.cs" />

    <Compile Include="$(BswmThisDir)ViewModels\DetailViewModel.cs" />
    <Compile Include="$(BswmThisDir)ViewModels\ExtraInfoViewModel.cs" />
    <Compile Include="$(BswmThisDir)ViewModels\MainViewModel.cs" />
    <Compile Include="$(BswmThisDir)ViewModels\ScoreEditorViewModel.cs" />
    <Compile Include="$(BswmThisDir)ViewModels\VictoryLineViewModel.cs" />
  </ItemGroup>

</Project>
