<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>WpfHelper</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <Platforms>x64;x86</Platforms>
    <RootNamespace>WpfHelper</RootNamespace>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Import Project="Props\OutputLibs.props" />

  <ItemGroup>
    <Compile Include="Common\AbstractSimpleCommand.cs" />
    <Compile Include="Common\INotifyCanExecuteChanged.cs" />
    <Compile Include="Common\SimpleCommand.cs" />

    <Compile Include="Document\LeagueInfo.cs" />

    <Compile Include="Models\RankingModel.cs" />

    <Compile Include="Services\IWindowService.cs" />

    <Compile Include="ViewModels\DetailViewModel.cs" />
    <Compile Include="ViewModels\ExtraInfoViewModel.cs" />
    <Compile Include="ViewModels\MainViewModel.cs" />
    <Compile Include="ViewModels\RankingViewModel.cs" />
    <Compile Include="ViewModels\ScoreEditorViewModel.cs" />
    <Compile Include="ViewModels\VictoryLineViewModel.cs" />
    <Compile Include="ViewModels\ViewModelBase.cs" />
  </ItemGroup>

</Project>
